### PR TITLE
Deepsource init & Fix Known Issues

### PR DESCRIPTION
**Pull request by loannaflip**
## Typo

* Section: [#training](https://github.com/JEF1056/Jv6#training)
	- Reccommended -> Recommended

### CODE REVIEW

**Comment by Uniminin** [comment]
Modules has been imported but is not used anywhere in the file. The module should either be used or the import should be removed.

**Comment by loannaflip** [comment]
Modules has been imported but is not used anywhere in the file. The module should either be used or the import should be removed.

**Comment by loannaflip** [comment]
I'd also recommend to add CD/CI. I'll leave it to yourself. All the best!

**Comment by loannaflip** [comment]
Dead. Closing.

**Pull request closed without merging**
